server:
  port: 8083

spring:
  application:
    name: chatgpt
  datasource:
    url: jdbc:postgresql://localhost:1234/postgres
    username: fiipractic
    password: fiipractic
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  openai:
    api_key: "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"