server:
  port: 8092

spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:1234/postgres
    username: fiipractic
    password: fiipractic
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true